baseURL = 'https://tmwalaszek.github.io/'
languageCode = 'en-us'
title = 'tmw'

[params]
  description = "A clean and simple blog"
  author = "Your Name"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = 'monokai'
    lineNos = true
    lineNumbersInTable = true
